### ISSUE TITLE
[建议]希望改变转换模式

### ISSUE THREAD

**Issue by taosuayou** [youzhazhu/Cloudflare-Workers-Download-Proxy#2]
将点击下载按钮后的自动下载转变为出现一个转换后的链接，操作者可以复制页面出现的链接，这对我来说很重要
抱歉，这是我第二次麻烦你了

**Comment by youzhazhu** [comment]
我想更多人应该需要自行跳转下载。
不过既然你有这个需求，那等我有空再改一下吧。

**Comment by youzhazhu** [comment]
你好，已经改好了。
增加了一个按钮，在网页上输出代理后的下载链接，应该可以满足你的需求了。
我想这个项目应该也没什么可更新的了，不过如果你还有疑问，欢迎提issue。

**Comment by taosuayou** [comment]
好的，谢谢昂
